name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: macwave.com.mx
        username: leoncito@macwave.com.mx
        password: ${{ secrets.FTP_PASSWORD }}
        local_path: ./
        remote_path: /home1/joeldura/public_html/
